# Generated by Django 2.0.2 on 2018-04-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180406_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('author', models.CharField(max_length=128)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(max_length=256)),
                ('topic', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('path', models.CharField(max_length=128)),
            ],
        ),
    ]
